# render.yaml
services:
  - type: web
    name: personal-profile
    env: static
    plan: free  # You can change this to a paid plan if needed
    staticPublishPath: .  # Path to your HTML files
    buildCommand: ""
    startCommand: ""
    routes:
      - type: web
        source: /
        destination: /
