# render.yaml
services:
  - type: web
    name: personal-profile
    env: static
    plan: free
    staticPublishPath: .  # Path to your HTML files
    buildCommand: ""
    startCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
